### ISSUE TITLE
Feedback: The bold text inside highlight could not be rendered

### ISSUE THREAD

**Issue by Moyf** [jancbeck/obsidian-omnireader#9]
See the image:
![Image](https://github.com/user-attachments/assets/018e217e-dc7b-42e9-a798-133c62a19b76)

---

BTW, it seems that in dark theme the text couldn't be seen clear for some color:
![Image](https://github.com/user-attachments/assets/87be17f4-54fe-4725-9ad1-153e31b3d20d)

Maybe use background color as text color?
```css
.theme-dark .omnidian-highlight {
    color: var(--background-primary) !important;
}
```

![Image](https://github.com/user-attachments/assets/3103921f-effb-4ab5-86ec-77c80e6fce5b)
